web:
  app:
    assets: assets
    port: 3030
    host: localhost
    viewDir: view
  cache:
    maxCacheSize: 104857600
    expire: 60000
  mysql:
    -
      name: local
      host: localhost
      user: root
      password: ''
      database: test
      connectionLimit: 20